const ADD_TODO = "ADD_TODO";
const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
const TOGGLE_TODO = "TOGGLE_TODO";
const VisibilityFilters = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_ACTIVE: "SHOW_COMPLETED",
};

export default {
  ADD_TODO,
  SET_VISIBILITY_FILTER,
  TOGGLE_TODO,
  VisibilityFilters
};
